# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5538169b918014af00140c0aaf3f2716b96ae6caec45a1f412e20e99b3f0c660a94d71cfdfce37272928fc7bfee295fbdc919abfe37a2b216d234a2d24766d

test:
  secret_key_base: c5b0cad8110432d29ab834e851d6375dce895fab9e4595eb4de9acbd09d62de0c04096896828afa7bda6c862bb626ffdde3b8215f649d0a725758464043a354e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
